import nodemailer from 'nodemailer';

function createTransport() {
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS, // Use an App Password for Gmail
    },
  });
}

export async function sendSummaryEmail(
  to: string[],
  subject: string,
  html: string,
  text: string,
  jsonAttachment?: object
): Promise<void> {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.warn('[MeetWise] EMAIL_USER / EMAIL_PASS not set — skipping email send.');
    return;
  }

  const transporter = createTransport();

  const attachments = jsonAttachment
    ? [
        {
          filename: 'meetwise-summary.json',
          content: JSON.stringify(jsonAttachment, null, 2),
          contentType: 'application/json',
        },
      ]
    : [];

  await transporter.sendMail({
    from: `"MeetWise AI" <${process.env.EMAIL_USER}>`,
    to: to.join(', '),
    subject,
    text,
    html,
    attachments,
  });
}

export function buildEmailHtml(summary: {
  title: string;
  tldr: string;
  key_takeaways: string[];
  decisions: { decision: string; rationale?: string }[];
  action_items: { task: string; owner: string; due: string; note?: string }[];
  suggested_followups: string[];
  confidence: number;
}): string {
  const decisionsHtml = summary.decisions
    .map(
      (d) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;">✅ ${d.decision}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;color:#5f5240;">${d.rationale ?? ''}</td>
      </tr>`
    )
    .join('');

  const actionItemsHtml = summary.action_items
    .map(
      (a) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;">📌 ${a.task}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;">${a.owner}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;">${a.due}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e4db;color:#5f5240;">${a.note ?? ''}</td>
      </tr>`
    )
    .join('');

  return `<!DOCTYPE html><html><body style="font-family:Georgia,serif;background:#f5f3ef;margin:0;padding:24px;">
  <div style="max-width:680px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08);">
    <div style="background:#2a241c;padding:32px;color:#f5f3ef;">
      <p style="margin:0 0 4px;font-size:12px;letter-spacing:.1em;opacity:.6;">MEETWISE AI SUMMARY</p>
      <h1 style="margin:0 0 12px;font-size:22px;">${summary.title}</h1>
      <p style="margin:0;font-size:15px;opacity:.85;">${summary.tldr}</p>
    </div>
    <div style="padding:24px;">
      <h2 style="font-size:14px;letter-spacing:.08em;color:#7d6e52;margin:0 0 12px;">KEY TAKEAWAYS</h2>
      <ul style="margin:0 0 24px;padding-left:20px;">
        ${summary.key_takeaways.map((k) => `<li style="margin-bottom:6px;">${k}</li>`).join('')}
      </ul>
      <h2 style="font-size:14px;letter-spacing:.08em;color:#7d6e52;margin:0 0 12px;">DECISIONS</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
        <thead><tr style="background:#f5f3ef;">
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Decision</th>
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Rationale</th>
        </tr></thead>
        <tbody>${decisionsHtml}</tbody>
      </table>
      <h2 style="font-size:14px;letter-spacing:.08em;color:#7d6e52;margin:0 0 12px;">ACTION ITEMS</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
        <thead><tr style="background:#f5f3ef;">
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Task</th>
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Owner</th>
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Due</th>
          <th style="padding:8px 12px;text-align:left;font-size:12px;">Note</th>
        </tr></thead>
        <tbody>${actionItemsHtml}</tbody>
      </table>
      <h2 style="font-size:14px;letter-spacing:.08em;color:#7d6e52;margin:0 0 12px;">SUGGESTED FOLLOW-UPS</h2>
      <ul style="margin:0 0 24px;padding-left:20px;">
        ${summary.suggested_followups.map((f) => `<li style="margin-bottom:6px;">${f}</li>`).join('')}
      </ul>
      <p style="font-size:12px;color:#9c8c6c;">AI confidence: ${Math.round(summary.confidence * 100)}% · Generated by MeetWise AI</p>
    </div>
  </div>
</body></html>`;
}

export function buildEmailText(summary: {
  title: string;
  tldr: string;
  key_takeaways: string[];
  decisions: { decision: string; rationale?: string }[];
  action_items: { task: string; owner: string; due: string; note?: string }[];
  suggested_followups: string[];
}): string {
  return [
    `MEETWISE AI SUMMARY`,
    `===================`,
    `${summary.title}`,
    ``,
    `TL;DR: ${summary.tldr}`,
    ``,
    `KEY TAKEAWAYS`,
    summary.key_takeaways.map((k) => `  • ${k}`).join('\n'),
    ``,
    `DECISIONS`,
    summary.decisions.map((d) => `  ✓ ${d.decision}${d.rationale ? ` — ${d.rationale}` : ''}`).join('\n'),
    ``,
    `ACTION ITEMS`,
    summary.action_items.map((a) => `  [${a.owner}] ${a.task} (Due: ${a.due})${a.note ? ` — ${a.note}` : ''}`).join('\n'),
    ``,
    `SUGGESTED FOLLOW-UPS`,
    summary.suggested_followups.map((f) => `  → ${f}`).join('\n'),
  ].join('\n');
}
